Grupa6-SANTeam-main/Implementacija/Implementacija/Models/Kolekcija.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Implementacija.Models
{
    public class Kolekcija
    {
        [Key]
        public int Id { get; set; }
        public string Naziv { get; set; }
        public int KorisnikId { get; set; }
        public Korisnik korisnik { get; set; }  
        public Kolekcija() { }

    }
}

Grupa6-SANTeam-main/Implementacija/Implementacija/Controllers/KolekcijaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Implementacija.Data;
using Implementacija.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;
using System.Net.Http;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Identity;

namespace Implementacija.Controllers
{
    [Authorize]
    public class KolekcijaController : Controller
    {
        private readonly IConfiguration _config;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public KolekcijaController(ApplicationDbContext context, IConfiguration config, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _config = config;
            _userManager = userManager;
        }

        // GET: Kolekcija
        public IActionResult Index()
        {
            var osoba = _context.Osoba.ToList().Find(o => o.UserId == _userManager.GetUserAsync(User).Result?.Id);
            var korisnik = _context.Korisnik.ToList().Find(k => k.osobaId == osoba.Id);
            var kolekcije = _context.Kolekcija.ToList().FindAll(k => k.KorisnikId == korisnik.Id);
            return View(kolekcije);
        }

        // GET: Kolekcija/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kolekcija = await _context.Kolekcija
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kolekcija == null)
            {
                return NotFound();
            }

            return View(kolekcija);
        }

        // GET: Kolekcija/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Kolekcija/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naziv")] Kolekcija kolekcija)
        {
            if (ModelState.IsValid)
            {
                //first create the collection
                //then create KolekcijaVeza to connect the current user with the collection
                var osoba= _context.Osoba.ToList().Find(o => o.UserId== _userManager.GetUserAsync(User).Result?.Id);
                var korisnik = _context.Korisnik.ToList().Find(k => k.osobaId == osoba.Id);

                kolekcija.KorisnikId = korisnik.Id;

                _context.Add(kolekcija);
                await _context.SaveChangesAsync();

                /*  if (korisnik != null)
                  { 
                      KolekcijaVeza kolekcijaVeza = new KolekcijaVeza
                      {
                          Korisnik = korisnik,
                          Kolekcija=kolekcija
                      };
                      _context.Add(kolekcijaVeza);
                      await _context.SaveChangesAsync();
                  }
                  else return NotFound();*/
            }
            return View(kolekcija);
        }

        // GET: Kolekcija/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kolekcija = await _context.Kolekcija.FindAsync(id);
            if (kolekcija == null)
            {
                return NotFound();
            }
            return View(kolekcija);
        }

        // POST: Kolekcija/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naziv")] Kolekcija kolekcija)
        {
            if (id != kolekcija.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var osoba = _context.Osoba.ToList().Find(o => o.UserId == _userManager.GetUserAsync(User).Result?.Id);
                    var korisnik = _context.Korisnik.ToList().Find(k => k.osobaId == osoba.Id);
                    kolekcija.KorisnikId = korisnik.Id;
                    _context.Update(kolekcija);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KolekcijaExists(kolekcija.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kolekcija);
        }

        // GET: Kolekcija/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kolekcija = await _context.Kolekcija
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kolekcija == null)
            {
                return NotFound();
            }

            return View(kolekcija);
        }

        // POST: Kolekcija/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kolekcija = await _context.Kolekcija.FindAsync(id);
            _context.Kolekcija.Remove(kolekcija);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KolekcijaExists(int id)
        {
            return _context.Kolekcija.Any(e => e.Id == id);
        }

        [HttpGet("/save/{movieId}/{title}")]
        public async Task<IActionResult> SaveMovieToCollection(int movieId, string title)
        {
            var movieApiKey = _config["TMDBApiKey"];
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"https://api.themoviedb.org/3/movie/{movieId}?api_key={movieApiKey}&language=en-US"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();

                    Film film = new Film();
                    ApiMovie ThisMovie = JsonConvert.DeserializeObject<ApiMovie>(apiResponse);

                    film.Naziv = ThisMovie.title;
                    film.Sinopsis = ThisMovie.overview;
                    film.Trajanje = (ThisMovie.runtime / 60).ToString() + ":" + ((int)ThisMovie.runtime % 60).ToString();
                    film.OcjenaIMDb = ThisMovie.vote_average;
                    film.GodinaObjave = int.Parse(ThisMovie.release_date.Split('-')[0]);
                    film.Slika = ThisMovie.poster_path;
                    film.tmbd_id = ThisMovie.id;
                    if (ThisMovie.genres != null)
                    {
                        foreach (var zanr in ThisMovie.genres)
                        {
                            if (film.Zanr == null) film.Zanr = zanr.name;
                            else film.Zanr = film.Zanr +"-"+ zanr.name;
                        }
                    }
                    if((_context.Film!=null && _context.Film.ToList() != null && _context.Film.ToList().Find(f =>f.Naziv==film.Naziv && f.Slika==film.Slika)==null) ||
                        _context.Film==null)
                    if (ModelState.IsValid)
                    {
                        _context.Add(film);
                        await _context.SaveChangesAsync();
                            //moram film ubaciti u kolekciju
                    }
                    ViewBag.filmId = _context.Film.ToList().Find(f => f.Naziv == film.Naziv && f.Slika == film.Slika).Id;
                }
            }
            var osoba = _context.Osoba.ToList().Find(o => o.UserId == _userManager.GetUserAsync(User).Result?.Id);
            var korisnik = _context.Korisnik.ToList().Find(k => k.osobaId == osoba.Id);
            var kolekcije = _context.Kolekcija.ToList().FindAll(k => k.KorisnikId == korisnik.Id);
            return View(kolekcije);
        }
        [HttpGet("/saveMovie/{movieId}/{collectionId}")]
        public async Task<IActionResult> SaveMovie(int movieId, int collectionId)
        {
            //moram kreirati objekat tipa medjutabele FilmVeza
            FilmVeza filmVeza = new FilmVeza
            {
                Kolekcija = _context.Kolekcija.ToList().Find(k => k.Id==collectionId),
                Film = _context.Film.ToList().Find(k => k.Id == movieId)
            };
            if (ModelState.IsValid)
            {
                if(_context.FilmVeza.ToList().Find(v => v.FilmId==movieId && v.KolekcijaId==collectionId)==null)
                _context.Add(filmVeza);
                await _context.SaveChangesAsync();
            }
            return View();
        }
    }
}

Grupa6-SANTeam-main/Implementacija/Implementacija/Views/Kolekcija/Create.cshtml
@model Implementacija.Models.Kolekcija

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Kolekcija</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Grupa6-SANTeam-main/Implementacija/Implementacija/Views/Kolekcija/Delete.cshtml
@model Implementacija.Models.Kolekcija

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kolekcija</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Grupa6-SANTeam-main/Implementacija/Implementacija/Views/Kolekcija/Details.cshtml
@model Implementacija.Models.Kolekcija

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Kolekcija</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Grupa6-SANTeam-main/Implementacija/Implementacija/Views/Kolekcija/Edit.cshtml
@model Implementacija.Models.Kolekcija

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Kolekcija</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Grupa6-SANTeam-main/Implementacija/Implementacija/Views/Kolekcija/Index.cshtml
@model IEnumerable<Implementacija.Models.Kolekcija>

@{
    ViewData["Title"] = "Index";
}

@if (User.Identity.IsAuthenticated)
 {


<style>
    body {
        color: snow;
        background-image: url("https://i.ibb.co/dGmJRcn/Pocetna-Stranica.png");
        height: 30%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
    }
    .User{
        width:100%;
        margin-bottom:5%;
    }
    .Lista {
        background-color: rgb(0, 0, 0,0.7);
        width:60%;     
    }
    .Create{
        float:right;
        width:10%;   
        margin-top:10%;
        margin-top:-8px;
    }
    .Lista li:hover{
        background-color: rgb(255, 255, 255,0.5);       
    } 
</style>

<div>
     <a sp-area="" asp-controller="Home" asp-action="Index">
    <img style="height:6em" src="https://i.ibb.co/n0bPk5B/logo-movie-removebg-preview.png" /><br />
    </a>
</div>

<div class="User">
    <center>
        <img style="height:5em" src="https://i.ibb.co/NyzBBdb/icons8-user-64.png" /><br />
        <p style="color:white;margin-left:10px;font-size:30px;margin-top:10px;font-weight:bold">@User.Identity.Name</p>
        <p style="color:white;margin-left:10px;font-size:25px;margin-top:10px">Your Collections</p>
    </center>
</div>
<div class="Create">
    <img style="height:5em" src="https://i.ibb.co/R3PTx6b/icons8-add-new-64.png" />
    <a asp-controller="Kolekcija" asp-action="Create" style="font-size:25px;margin-left:5px;color:white">Create</a>
</div>

<div class="Lista">

@foreach (var item in Model) {
        <ul>
            
            <li style="font-size:30px">
               <a href="/filmovi/@item.Id"> @Html.DisplayFor(modelItem => item.Naziv) </a>

                <a asp-action="Delete" asp-route-id="@item.Id" 
                style="float:right;margin-right:12px;color:rgb(143, 0, 0);font-size:20px">Delete</a>
            </li>
       
        </ul>
}
</div>

}

Grupa6-SANTeam-main/Implementacija/Implementacija/Views/Kolekcija/SaveMovie.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div style="width:100%">
   <center>
       <div style="width:400px;margin-top:20%;background-color: rgb(0, 0, 0,0.7);border:2px solid gray;">
           <center><h1>Succesful!</h1></center>
       </div>
   </center>
</div>
<style>
body {
        color: snow;
        background-image: url("https://i.ibb.co/dGmJRcn/Pocetna-Stranica.png");
        height: 50%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
}</style>

Grupa6-SANTeam-main/Implementacija/Implementacija/Views/Kolekcija/SaveMovieToCollection.cshtml
@model IEnumerable<Implementacija.Models.Kolekcija>

@{
    ViewData["Title"] = "SaveMovieToCollection";
}


@if (User.Identity.IsAuthenticated)
 {


<style>
    body {
        color: snow;
        background-image: url("https://i.ibb.co/dGmJRcn/Pocetna-Stranica.png");
        height: 30%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
    }
    .User{
        width:100%;
        margin-bottom:5%;
    }
    .Lista {
        background-color: rgb(0, 0, 0,0.7);
        width:60%;     
    }
    .Create{
        float:right;
        width:10%;   
        margin-top:10%;
    }
    .Lista li:hover{
        background-color: rgb(255, 255, 255,0.5);       
    }
   
   
</style>

<div class="User">
    <center>
        <img style="height:5em" src="https://i.ibb.co/NyzBBdb/icons8-user-64.png" /><br />
        <p style="color:white;margin-left:10px;font-size:30px;margin-top:10px;font-weight:bold">@User.Identity.Name</p>
        <p style="color:white;margin-left:10px;font-size:25px;margin-top:10px">Your Collections</p>
    </center>
</div>
<div class="Lista">
    <div>
@foreach (var item in Model) {
        <ul>
            <li style="font-size:30px">
                @Html.DisplayFor(modelItem => item.Naziv)
                <a href="/saveMovie/@ViewBag.filmId/@item.Id"
                style="float:right;margin-right:5px;color:yellow;font-size:20px">Save
                </a>
            </li>
        </ul>
}
</div>
</div>




}